### ISSUE TITLE
Does it work? v2

### ISSUE THREAD

**Issue by OrsonDeWitt** [tylerbrockett/reddit-bot-buildapcsales#12]
Hi, thanks for your work!
After I set up the bot to send me posts with a specific title, I tried messaging "subs" to it and got the reply that everything was set correctly. But when I posted a post on the chosen subreddit, I didn't get any messages from alertbot.
Thanks

**Comment by tylerbrockett** [comment]
How long did you wait after submitting the post?

The bot's alerts aren't instantaneous. It may take quite some time to parse through all the subscription's subreddits and send alerts to everyone.

Reddit limits you to one request per second or something like that, so if there's a post that matches a LOT of people's subscriptions, it can take quite some time to cycle through.

**Comment by OrsonDeWitt** [comment]
I created the post in a subreddit with 8 people to test it, and I wanted for half an hour. How often does it check/update? :)

**Comment by APost-It** [comment]
I haven't received a message from alert_bot for 3 months. alert_bot responds to "subs" and new subscribes. I have four subscriptions and the last message from alert_bot in each is from 3 months ago. For what it's worth, I ended one of my subs 1 month ago, and then immediately resubscribed using the same parameters. alert_bot responded as it should, but I haven't received any messages since then, despite me finding things that it should have reported.

**Comment by APost-It** [comment]
I'm not sure if there has been any updates to alert_bot but I'd like to update that I just received my first message from alert_bot in 4 months about 10 hours ago. Since then I've received 10 messages from it. This is the usual behavior I've been expecting from alert_bot.

**Comment by tylerbrockett** [comment]
@APost-It, Yes, I made a couple minor changes with how errors are handled last night, a PR is incoming (wanted to test on my dev machine for a bit before committing the changes).

I've been very busy with work the last few months, so I haven't had time to fix the bot. I apologize, and also greatly appreciate your comment confirming that things are working better now.

**Comment by APost-It** [comment]
Keep up the good work. I love alert_bot.
