### ISSUE TITLE
/r/hardwareswap ?

### ISSUE THREAD

**Issue by peoplma** [tylerbrockett/reddit-bot-buildapcsales#3]
Hey, great bot!  How hard would it be to add in support for subscribing to /r/hardwareswap in a similar manner to how it works for /r/buildapcsales?

**Comment by tylerbrockett** [comment]
Thanks!

I would likely create an entirely separate bot for that. It should just require changing the subreddit it looks at, the rest should be identical. 

Edit: mods at /r/hardwareswap denied the request since IFTTT and push bullet can basically do the same thing.

**Comment by tylerbrockett** [comment]
Hey @peoplma,

I just wanted to let you know that I'm working on changing the bot to allow ANY subreddit, /r/hardwareswap included. It won't be available for a little while still, but just know that it is coming and to keep an eye out for it. If you message /u/tylerbrockett on Reddit, I'll make sure to message you when it does become available.

Thanks again!
-Tyler

**Comment by tylerbrockett** [comment]
Also note that it won't be an official /r/hardwareswap bot by any means like it sort of is for /r/buildapcsales, I still haven't mentioned this to the mods. I likely will when it comes closer to the time of release, we'll see. Since it's gonna be opened up to all subreddits, I may make a separate subreddit for the bot. Again, we'll see!
