### ISSUE TITLE
Subscribe to all subreddits?

### ISSUE THREAD

**Issue by orschiro** [tylerbrockett/reddit-bot-buildapcsales#8]
Hi all, 

Is it possible to watch entire Reddit (instead of just a specific subreddit) for a specific keyword in either title or body?

Thanks!

**Comment by tylerbrockett** [comment]
Short answer is it is not recommended.

I don't remember if the bot allows it, but you might be able to do something like

`subscribe -title keyword -subreddit /r/all`

Problem there is, because of the extremely high number of posts in /r/all, and the bot only polling once every few minutes, it is bound to miss a lot of the posts.
